name: pipeline

on:
  - push
  - pull_request

jobs:

  nix:
    name: nix-${{ matrix.os }}-${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ghc:
          - ghc8104
          - ghc884
          - ghc865
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: setup-nix
        uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
          extra_nix_config: |
            substituters = https://cache.nixos.org https://hydra.iohk.io
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=

      - name: setup-cachix
        uses: cachix/cachix-action@v10
        with:
          name: asterius
          extraPullNames: niv
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

      - name: test
        run: |
          nix-build --keep-going --argstr ghc ${{ matrix.ghc }} . -A hs-wasmtime

      - name: test-nix-shell
        run: |
          nix-shell --pure --keep-going --argstr ghc ${{ matrix.ghc }} --run "cabal v2-run hs-wasmtime-test"

          nix-shell --pure --keep-going --argstr ghc ${{ matrix.ghc }} --run "haskell-language-server typecheck"
